### ISSUE TITLE
Traducción 

### ISSUE THREAD

**Issue by ardillas-ff** [JaquerEspeis/privacidad-queer#14]
Yo me apunto a traducir, necesito el libro nada más. Empecé a traducir _What's in a name_ hasta que vi que ya lo habían empezado. Puedo echarle un ojo a ese cuando lo tengan listo también

**Comment by come-maiz** [comment]
@ardillas-ff ¿a dónde se lo envío?

**Comment by ardillas-ff** [comment]
FdesamparadosF@protonmail.com

**Comment by come-maiz** [comment]
Enviado.
